// Self-test questions per track. Each: tag, q, c (choices), a (index of the correct choice),
// e (explanation), ref (module "F3" or section "F3.4" to reread).
const q = (tag, question, choices, answer, explanation, ref) => ({ tag, q: question, c: choices, a: answer, e: explanation, ref });

// Questions shared by several tracks
const WEB = [
  q('Web', 'Which HTTP methods are idempotent?', ['POST and PATCH', 'GET, PUT and DELETE', 'Only GET', 'POST, PUT and DELETE'], 1, 'Repeating GET, PUT or DELETE leaves the server in the same state; POST and PATCH are not guaranteed to.', 'S1.4'),
  q('Web', 'A logged-in accountant calls an admin-only endpoint. The correct status is…', ['401 Unauthorized', '403 Forbidden', '404 Not Found', '400 Bad Request'], 1, '401 means not authenticated; 403 means authenticated but not allowed.', 'S1.4'),
  q('Web', 'Your Angular app on localhost:4200 gets a CORS error calling an API on localhost:5000. Who must fix it?', ['The browser settings', 'The API, by allowing that origin', 'Angular, by disabling security', 'Nobody: Postman works, so it is fine'], 1, 'CORS is the server opting in to let another origin read its responses; it is enforced only by browsers.', 'S1.7'),
  q('Web', 'Which cookie attribute stops JavaScript from reading a session cookie?', ['Secure', 'SameSite=Strict', 'HttpOnly', 'Max-Age'], 2, 'HttpOnly hides the cookie from document.cookie, so XSS cannot steal it.', 'S1.6'),
  q('Web', 'How should hashed asset files (main.3f9a.js) be cached?', ['no-store', 'no-cache', 'Long max-age with immutable', 'Not cached at all'], 2, 'A new build changes the file name, so the old file can be cached forever; index.html gets no-cache.', 'S1.8'),
];
const GIT = [
  q('Git', 'You need to undo a commit that is already pushed to a shared branch. Use…', ['git reset --hard', 'git revert', 'git commit --amend', 'git rebase -i'], 1, 'Revert adds a new commit that undoes the old one without rewriting shared history.', 'S2.5'),
  q('Git', 'You accidentally committed an API key and pushed it. The FIRST step is…', ['Delete it in a new commit', 'Rotate the key', 'Rewrite history with filter-repo', 'Make the repo private'], 1, 'Once pushed, the secret is compromised: rotate it first, then clean history.', 'S2.8'),
  q('Git', 'Which statement about rebase is true?', ['It never changes commit hashes', 'It is safe on branches others have pulled', 'It replays commits on a new base, creating new hashes', 'It always creates a merge commit'], 2, 'Rebase rewrites history, so only rebase work nobody else has based commits on.', 'S2.3'),
];
const SQL = [
  q('SQL', 'Which clause filters groups after aggregation?', ['WHERE', 'HAVING', 'ORDER BY', 'ON'], 1, 'WHERE filters rows before grouping; HAVING filters groups after.', 'S3.2'),
  q('SQL', 'NOT IN (subquery) returns no rows at all. The likely cause is…', ['A missing index', 'A NULL in the subquery result', 'Integer division', 'A missing GROUP BY'], 1, 'x <> NULL is UNKNOWN, so no row qualifies; use NOT EXISTS.', 'S3.3'),
  q('SQL', 'For values 100, 90, 90, 80, DENSE_RANK gives…', ['1, 2, 3, 4', '1, 2, 2, 4', '1, 2, 2, 3', '1, 1, 2, 3'], 2, 'DENSE_RANK leaves no gap after ties; RANK gives 1, 2, 2, 4.', 'S3.7'),
  q('SQL', 'After a LEFT JOIN customers→orders you add WHERE o.status = \'paid\'. What happens?', ['Nothing changes', 'Customers without orders disappear', 'It becomes a FULL JOIN', 'It errors'], 1, 'NULL statuses fail the WHERE, turning it into an inner join; put the condition in ON.', 'S3.4'),
];
const BEHAVE = [
  q('Hiring', 'Under Egypt\'s Labour Law No. 14 of 2025, probation may last at most…', ['One month', 'Three months, once per employer', 'Six months', 'One year'], 1, 'At most three months, and an employer may apply probation only once.', 'S8.8'),
  q('Hiring', 'In a STAR answer, most of your time should go on…', ['Situation', 'Task', 'Action', 'Result'], 2, 'Interviewers hire you for what you did: spend most of the answer on your actions.', 'S8.3'),
];

module.exports = {
  fe: [
    ...WEB, ...GIT.slice(0, 2),
    q('HTML', 'Why use <button> instead of <div onclick>?', ['It looks better', 'It is focusable, keyboard-operable and announced as a button', 'Divs cannot have click handlers', 'Buttons load faster'], 1, 'Native elements bring focus, Enter/Space activation and the right role for free.', 'F1.1'),
    q('A11y', 'What is the first rule of ARIA?', ['Add ARIA to every element', 'Use native HTML when it already provides the semantics and behaviour', 'Always use role="button"', 'ARIA replaces labels'], 1, 'ARIA describes but adds no behaviour; native elements are preferred.', 'F1.7'),
    q('A11y', 'Minimum WCAG AA contrast for normal body text?', ['3:1', '4.5:1', '7:1', '2:1'], 1, '4.5:1 for normal text; 3:1 for large text and UI components.', 'F1.8'),
    q('A11y', 'Which is new in WCAG 2.2 at level AA?', ['Alt text for images', 'Target size of at least 24×24 CSS pixels', 'Captions for video', 'A lang attribute'], 1, '2.5.8 Target Size (Minimum) is new in 2.2, along with focus-not-obscured and others.', 'F1.5'),
    q('CSS', 'Specificity of .card .title:hover is…', ['(0,1,1)', '(0,2,1)', '(0,3,0)', '(1,0,0)'], 2, 'Two classes plus one pseudo-class = three in the middle column.', 'F2.1'),
    q('CSS', 'z-index: 9999 still sits under another element. The most likely cause is…', ['Browser bug', 'A stacking context created by an ancestor (transform, opacity…)', 'z-index has a maximum of 999', 'Flexbox ignores z-index'], 1, 'A child cannot rise above its stacking context\'s siblings.', 'F2.3'),
    q('CSS', 'Which tool fits a page layout with rows and columns that must align?', ['Flexbox', 'Grid', 'Floats', 'Tables'], 1, 'Grid is two-dimensional and layout-driven.', 'F2.5'),
    q('JS', 'for (var i=0;i<3;i++) setTimeout(()=>console.log(i)) prints…', ['0 1 2', '3 3 3', '0 0 0', 'undefined ×3'], 1, 'var has one function-scoped binding; let would create one per iteration.', 'F3.4'),
    q('JS', 'What does 0 ?? 10 evaluate to?', ['10', '0', 'null', 'undefined'], 1, '?? only falls back on null or undefined; || would give 10.', 'F3.2'),
    q('JS', 'Which array method does NOT mutate the array?', ['sort()', 'splice()', 'toSorted()', 'reverse()'], 2, 'toSorted (ES2023) returns a sorted copy.', 'F3.7'),
    q('JS', 'Order of output: setTimeout(…,0), Promise.resolve().then(…), plain console.log?', ['timeout, promise, sync', 'sync, promise, timeout', 'promise, sync, timeout', 'sync, timeout, promise'], 1, 'Sync code first, then all microtasks (promises), then the next task (timer).', 'F4.2'),
    q('JS', 'Does fetch reject on an HTTP 500 response?', ['Yes', 'No, check response.ok', 'Only in Chrome', 'Only for POST'], 1, 'fetch rejects only on network failure.', 'F4.5'),
    q('JS', 'One listener on a <ul> handling clicks on all <li>s is called…', ['Event capturing', 'Event delegation', 'Debouncing', 'Throttling'], 1, 'Delegation relies on bubbling and event.target.', 'F4.6'),
    q('TS', 'Which type forces you to narrow before use?', ['any', 'unknown', 'never', 'void'], 1, 'unknown accepts anything but must be narrowed; any disables checking.', 'F5.6'),
    q('TS', 'Does TypeScript validate API responses at runtime?', ['Yes, automatically', 'No, types are erased; validate with a schema such as Zod', 'Only with strict mode', 'Only interfaces do'], 1, 'Types vanish after compilation.', 'F5.9'),
    q('React', 'Why avoid array indexes as keys in a list that can be reordered?', ['They are slower', 'State and DOM can attach to the wrong item', 'React forbids numbers', 'They break SSR'], 1, 'React matches items by key; indexes shift when items move.', 'F6.2'),
    q('React', 'setCount(count+1) three times in one handler increases count by…', ['3', '1', '0', 'It throws'], 1, 'Each call uses the same render\'s count; use setCount(c => c + 1).', 'F6.2'),
    q('React', 'Which is the WRONG use of useEffect?', ['Subscribing to a WebSocket', 'Computing a filtered list from props', 'Starting an interval with clean-up', 'Integrating a non-React widget'], 1, 'Derived data should be computed during render, not in an effect.', 'F6.3'),
    q('React', 'What did the React Compiler (v1.0, Oct 2025) add?', ['Server Components', 'Automatic memoisation at build time', 'A new router', 'TypeScript support'], 1, 'It removes most manual useMemo/useCallback/memo.', 'F6.6'),
    q('Angular', 'In search-as-you-type, which RxJS operator cancels stale requests?', ['mergeMap', 'concatMap', 'switchMap', 'exhaustMap'], 2, 'switchMap unsubscribes from the previous inner observable.', 'F7.6'),
    q('Angular', 'Since Angular 22, the default change-detection strategy for components is…', ['Default (eager)', 'OnPush', 'Manual', 'Zone-only'], 1, 'v22 (June 2026) made OnPush the default; v21 made zoneless the default.', 'F7.4'),
    q('Angular', 'Is a route guard a security control?', ['Yes, it is enough', 'No, it is UX; the API must authorise every request', 'Only canMatch is', 'Only with JWT'], 1, 'Anyone can call the API directly.', 'F7.8'),
    q('State', 'Where should filters and the page number of a list live?', ['localStorage', 'A global store', 'The URL', 'A cookie'], 2, 'URL state survives refresh and can be shared.', 'F8.6'),
    q('State', 'After creating an invoice, how do you refresh the cached list in TanStack Query?', ['Reload the page', 'Invalidate its query key', 'Increase staleTime', 'Clear localStorage'], 1, 'Invalidation marks queries stale so active ones refetch.', 'F8.2'),
    q('Perf', 'Which Core Web Vital replaced FID in March 2024?', ['LCP', 'CLS', 'INP', 'TTFB'], 2, 'INP measures responsiveness across all interactions.', 'F9.1'),
    q('Perf', 'Good LCP at the 75th percentile is…', ['≤ 1 s', '≤ 2.5 s', '≤ 4 s', '≤ 200 ms'], 1, 'LCP ≤ 2.5 s, INP ≤ 200 ms, CLS ≤ 0.1.', 'F9.1'),
    q('Perf', 'Lazy-loading the hero (largest above-the-fold) image will…', ['Improve LCP', 'Delay LCP', 'Improve CLS', 'Have no effect'], 1, 'The LCP element should load early with fetchpriority=high.', 'F9.3'),
    q('Perf', 'What is hydration?', ['Compressing assets', 'Attaching JS behaviour to server-rendered HTML', 'Caching API calls', 'Pre-fetching routes'], 1, 'Until hydration finishes, the page may look ready but not respond.', 'F9.7'),
    q('Testing', 'Which Testing Library query should you prefer?', ['getByTestId', 'getByRole', 'container.querySelector', 'getByClassName'], 1, 'Role queries mirror how users find elements and check accessibility.', 'F10.4'),
    q('Testing', 'A test sometimes fails without code changes. A common cause is…', ['Too many assertions', 'Fixed sleeps or shared state between tests', 'Using TypeScript', 'Using Vitest'], 1, 'Wait for conditions, isolate state, control time.', 'F10.8'),
    q('Security', 'Which is the strongest XSS defence among these?', ['Hiding admin buttons', 'Framework escaping plus a strict CSP and no innerHTML with user data', 'Using HTTPS', 'Minifying JS'], 1, 'Contextual encoding plus CSP; HttpOnly cookies limit the damage.', 'S9.4'),
    q('DSA', 'Membership checks inside a loop over a List<T> make an algorithm…', ['O(n)', 'O(n log n)', 'O(n²)', 'O(1)'], 2, 'List.Contains is O(n); use a HashSet for O(1) lookups.', 'S4.3'),
    ...BEHAVE,
  ],

  be: [
    ...WEB.slice(0, 3), ...GIT.slice(0, 2), ...SQL,
    q('C#', 'A value-type field inside a class instance is stored…', ['Always on the stack', 'On the heap with the object', 'In a register', 'In static memory'], 1, 'Value types live where their container lives; the real difference is copy semantics.', 'B1.2'),
    q('C#', 'Two records with equal property values compare as…', ['Not equal (reference equality)', 'Equal (value equality)', 'It depends on the hash', 'Compile error'], 1, 'Records get compiler-generated value equality.', 'B1.3'),
    q('C#', 'db.Invoices.ToList().Where(i => i.CompanyId == id) causes…', ['One efficient SQL query', 'Loading the whole table into memory, then filtering', 'A compile error', 'An N+1 problem'], 1, 'ToList materialises everything; keep it IQueryable until filtering.', 'B1.6'),
    q('C#', 'Why avoid .Result on an incomplete Task in ASP.NET code?', ['It is slower to type', 'It blocks a thread and can deadlock', 'It throws always', 'It disables logging'], 1, 'Stay async all the way.', 'B1.7'),
    q('C#', 'Objects of what size go to the Large Object Heap?', ['≥ 1 KB', '≥ 85,000 bytes', '≥ 1 MB', 'Any array'], 1, 'Objects of 85,000 bytes or more go to the LOH.', 'B1.8'),
    q('C#', 'A singleton service injects a scoped DbContext. This is…', ['Recommended', 'A captive dependency bug', 'Required for EF Core', 'Fine with AddTransient'], 1, 'Use IServiceScopeFactory and a scope per unit of work.', 'B1.11'),
    q('C#', 'throw; vs throw ex; inside a catch block?', ['Identical', 'throw; keeps the original stack trace', 'throw ex; keeps the stack trace', 'throw; swallows the exception'], 1, 'throw ex; resets the stack trace to the current line.', 'B1.9'),
    q('Design', 'Which principle says subtypes must be usable wherever the base type is?', ['Single responsibility', 'Open/closed', 'Liskov substitution', 'Interface segregation'], 2, 'An override throwing NotSupported is a typical violation.', 'B2.2'),
    q('Design', 'ASP.NET Core middleware is an example of which pattern?', ['Singleton', 'Chain of Responsibility', 'Observer', 'Builder'], 1, 'Each middleware handles or passes on the request.', 'B2.4'),
    q('ASP.NET', 'Where must the exception-handling middleware go?', ['Last', 'First (outermost)', 'After authorization', 'It does not matter'], 1, 'It only catches exceptions from components registered after it.', 'B3.2'),
    q('ASP.NET', 'With [ApiController], an invalid model automatically returns…', ['200 with errors', '400 ValidationProblemDetails', '500', '422 always'], 1, 'Automatic 400 responses are an [ApiController] behaviour.', 'B3.3'),
    q('ASP.NET', 'Why use IHttpClientFactory instead of new HttpClient() per call?', ['It is required by .NET 10', 'It pools handlers, avoiding socket exhaustion and stale DNS', 'It disables TLS', 'It caches responses'], 1, 'Typed clients plus resilience handlers are the recommended pattern.', 'B3.9'),
    q('API', 'Deep pages with OFFSET pagination are slow because…', ['Indexes are ignored', 'The database still reads and discards skipped rows', 'JSON gets larger', 'HTTP/2 limits it'], 1, 'Keyset pagination seeks directly past the last key.', 'B4.3'),
    q('API', 'How do you make a payment POST safe to retry?', ['Use GET instead', 'An Idempotency-Key header with stored results', 'Return 202', 'Disable retries'], 1, 'The same key returns the stored response without charging twice.', 'B4.4'),
    q('API', 'Two users edit the same invoice; how do you prevent a lost update?', ['Pessimistic locks for hours', 'Optimistic concurrency with ETag/If-Match or rowversion', 'Last write wins', 'Disable editing'], 1, 'A stale version returns 412 or 409.', 'B4.5'),
    q('EF Core', 'Including two collection navigations in one query can cause…', ['N+1', 'Cartesian explosion', 'Deadlocks', 'Client evaluation'], 1, 'Use AsSplitQuery or projection.', 'B5.5'),
    q('EF Core', 'What does AsNoTracking do?', ['Disables SQL logging', 'Skips change-tracking snapshots for read-only queries', 'Prevents lazy loading only', 'Uses a different database'], 1, 'Less memory and CPU for reads.', 'B5.5'),
    q('EF Core', 'What do EF Core 10 named query filters enable?', ['Faster joins', 'Ignoring one filter (e.g. soft delete) while keeping another (tenant)', 'Raw SQL injection', 'Multiple DbContexts'], 1, 'Before EF 10, IgnoreQueryFilters removed all filters at once.', 'B5.6'),
    q('Database', 'WHERE YEAR(order_date) = 2026 is slow on an indexed column because…', ['YEAR is deprecated', 'Wrapping the column makes the predicate non-sargable', 'Dates cannot be indexed', 'It scans only one partition'], 1, 'Use a half-open date range instead.', 'B6.4'),
    q('Database', 'Which anomaly does READ COMMITTED still allow?', ['Dirty reads', 'Lost updates', 'Neither', 'Only phantoms'], 1, 'It only prevents dirty reads; handle lost updates explicitly.', 'B6.5'),
    q('Auth', 'Is a JWT payload encrypted?', ['Yes, always', 'No, it is Base64url-encoded and signed', 'Only with RS256', 'Only in .NET'], 1, 'Never put secrets in a JWT.', 'B7.2'),
    q('Auth', 'Which OAuth flow should a SPA use?', ['Implicit', 'Resource owner password', 'Authorization code with PKCE', 'Client credentials'], 2, 'Implicit and password grants are deprecated (RFC 9700).', 'B7.5'),
    q('Caching', 'What must a cache key for a dashboard include in a multi-tenant app?', ['Nothing else', 'The tenant (and any other dimension the data depends on)', 'Only the user agent', 'The server name'], 1, 'Otherwise one tenant may see another\'s numbers.', 'B8.2'),
    q('Messaging', 'Most brokers deliver messages…', ['Exactly once', 'At least once, so consumers must be idempotent', 'At most once always', 'In global order'], 1, 'Duplicates happen after crashes and redeliveries.', 'B8.5'),
    q('Messaging', 'Saving to the database and publishing an event reliably requires…', ['Two separate calls', 'The transactional outbox pattern', 'A distributed transaction always', 'Publishing first'], 1, 'Write the event in the same transaction, publish later.', 'B8.7'),
    q('Architecture', 'Clean Architecture\'s dependency rule says dependencies point…', ['Outward to frameworks', 'Inward toward the domain', 'Sideways', 'Both ways'], 1, 'Infrastructure implements interfaces the core defines.', 'B9.2'),
    q('Architecture', 'Transactions across microservices are usually handled with…', ['Two-phase commit everywhere', 'Sagas with compensating actions', 'Shared databases', 'Global locks'], 1, 'Local transactions plus compensation.', 'B9.7'),
    q('Testing', 'Why avoid EF Core\'s InMemory provider for integration tests?', ['It is slow', 'It is not relational, so real SQL bugs slip through', 'It is deprecated', 'It needs Docker'], 1, 'Use Testcontainers with the real engine.', 'B10.5'),
    q('Testing', 'How do you test code that depends on the current time?', ['Mock DateTime.Now', 'Inject TimeProvider and use FakeTimeProvider', 'Run tests at midnight', 'Use Thread.Sleep'], 1, 'TimeProvider is built into .NET 8+.', 'B10.3'),
    q('Ops', 'The database belongs in which health probe?', ['Liveness', 'Readiness', 'Neither', 'Both'], 1, 'Failing liveness restarts every instance during a DB blip.', 'B11.6'),
    q('Ops', 'Retries are safe for which failures?', ['Any failure', 'Transient failures on idempotent operations, with backoff and jitter', 'Only 400 errors', 'Only POSTs'], 1, 'And retry at one layer only.', 'B11.8'),
    q('Design', '1 million requests per day is roughly how many per second on average?', ['1', '12', '120', '1,200'], 1, '1 day ≈ 10⁵ seconds; plan for peaks several times higher.', 'B12.2'),
    q('Node', 'What blocks Node\'s event loop?', ['Awaiting a database call', 'Synchronous CPU-heavy work', 'Network I/O', 'Timers'], 1, 'Waiting is free; computing blocks every request.', 'B13.1'),
    q('Cloud', 'AZ-204 (Azure Developer Associate) is…', ['The newest exam', 'Retired on 31 July 2026, succeeded by AI-200', 'Renamed DP-700', 'Free'], 1, 'Check certification status before studying.', 'S10.9'),
    ...BEHAVE,
  ],

  fs: [
    ...WEB, ...GIT.slice(0, 2), ...SQL.slice(0, 2),
    q('JS', 'Order of output: setTimeout(…,0), Promise.resolve().then(…), plain console.log?', ['timeout, promise, sync', 'sync, promise, timeout', 'promise, sync, timeout', 'sync, timeout, promise'], 1, 'Sync code, then microtasks, then the next task.', 'F4.2'),
    q('TS', 'Does TypeScript validate API responses at runtime?', ['Yes', 'No, types are erased; validate with a schema', 'Only with strict mode', 'Only with interfaces'], 1, 'Generate types from OpenAPI and validate at the boundary.', 'F5.9'),
    q('React', 'Why avoid index keys in a reorderable list?', ['Performance only', 'State attaches to the wrong item', 'React forbids it', 'SEO'], 1, 'Use stable IDs.', 'F6.2'),
    q('Angular', 'Which operator ignores repeated clicks until the current submit finishes?', ['switchMap', 'mergeMap', 'concatMap', 'exhaustMap'], 3, 'exhaustMap ignores new triggers while an inner call runs.', 'F7.6'),
    q('State', 'Server data such as invoices belongs in…', ['A global Redux store', 'A server-state cache (TanStack Query, httpResource)', 'localStorage', 'Component state only'], 1, 'Caching, refetching and invalidation come for free.', 'F8.1'),
    q('C#', 'IEnumerable vs IQueryable: which lets EF Core filter in SQL?', ['IEnumerable', 'IQueryable', 'Both equally', 'Neither'], 1, 'IQueryable keeps an expression tree for translation.', 'B1.6'),
    q('C#', 'A singleton injecting a scoped DbContext is…', ['Fine', 'A captive dependency', 'Required', 'Faster'], 1, 'Create a scope per unit of work.', 'B1.11'),
    q('ASP.NET', 'Exception handler middleware belongs…', ['Last', 'First', 'After endpoints', 'Anywhere'], 1, 'It catches exceptions from everything registered after it.', 'B3.2'),
    q('API', 'Large, changing lists should use…', ['Offset pagination', 'Keyset (cursor) pagination', 'No pagination', 'GraphQL only'], 1, 'Stable and constant cost.', 'B4.3'),
    q('EF Core', 'A query per invoice inside a loop is…', ['Cartesian explosion', 'N+1', 'Client evaluation', 'Lazy evaluation'], 1, 'Fix with Include, projection or batching.', 'B5.5'),
    q('Auth', 'Which flow should a SPA use with an identity provider?', ['Implicit', 'Password grant', 'Authorization code + PKCE', 'Client credentials'], 2, 'Ideally through a backend-for-frontend.', 'B7.5'),
    q('Full-stack', 'Same-origin deployment (reverse proxy serving SPA and /api) means…', ['CORS must allow credentials', 'No CORS configuration is needed and cookies are first-party', 'Cookies are blocked', 'You need two TLS certificates'], 1, 'One host, so the browser sees one origin.', 'FS1.1'),
    q('Full-stack', 'How do you keep TypeScript DTOs in sync with ASP.NET Core?', ['Copy them by hand', 'Generate them from the OpenAPI document and check drift in CI', 'Use any', 'Share a DLL'], 1, 'Generated clients cannot silently drift.', 'FS1.2'),
    q('Full-stack', 'Putting an API key in environment.prod.ts is…', ['Safe because it is compiled', 'Unsafe: front-end bundles are public', 'Safe with minification', 'Required for Angular'], 1, 'Only non-secret values belong in front-end config.', 'FS1.4'),
    q('Full-stack', 'app.example.com calling api.example.com is…', ['Same-origin and same-site', 'Cross-origin but same-site', 'Cross-origin and cross-site', 'Same-origin but cross-site'], 1, 'CORS works on origins; SameSite cookies on sites.', 'FS2.2'),
    q('Full-stack', 'Why make token refresh "single-flight" in the client?', ['To save bandwidth', 'Parallel refreshes with rotation trigger reuse detection and logout', 'Browsers allow one request', 'For SEO'], 1, 'Share one refresh between all waiting requests.', 'FS2.3'),
    q('Full-stack', 'With cookie auth, CSRF is mitigated by…', ['localStorage', 'SameSite cookies plus an anti-forgery header', 'HTTPS alone', 'CORS'], 1, 'Angular HttpClient sends X-XSRF-TOKEN automatically for mutating requests.', 'FS2.2'),
    q('Full-stack', 'How should a SignalR connection learn the tenant?', ['From a client-sent parameter', 'From the authenticated token\'s claim, on the server', 'From the URL', 'From localStorage'], 1, 'Never trust the client for group membership.', 'FS2.8'),
    q('Features', 'A 500 MB upload should go…', ['Through the API in one request', 'Directly to blob storage with a short-lived pre-signed URL', 'Into the database', 'Over WebSockets'], 1, 'Then a worker processes it.', 'FS3.1'),
    q('Features', 'Which event may mark an order as paid?', ['The browser success redirect', 'A verified, signed server-to-server webhook', 'A client-side callback', 'An email'], 1, 'Redirects can be faked or never arrive.', 'FS3.3'),
    q('Features', 'Why not hard-code Cairo as UTC+2?', ['It is UTC+1', 'Egypt reinstated daylight saving time in 2023', 'Time zones do not matter', 'Browsers forbid it'], 1, 'Use the IANA zone Africa/Cairo.', 'FS3.6'),
    q('Features', 'LLM calls in a web app should be made…', ['From the browser with the API key', 'From the server, with tenant-scoped retrieval and budgets', 'Only via WebSockets', 'Without logging'], 1, 'Keys and authorisation stay server-side.', 'FS3.8'),
    q('Ship', 'Database migrations in a live system should be…', ['Applied by every app instance at startup', 'Backward compatible (expand and contract), run by the pipeline', 'Rolled back with down-migrations', 'Skipped'], 1, 'So the running version keeps working and rollback is possible.', 'S10.3'),
    q('Ship', 'How can CI deploy to Azure without a stored secret?', ['Disable auth', 'OIDC workload identity federation', 'Put the key in the repo', 'Use FTP'], 1, 'Azure trusts GitHub\'s short-lived token.', 'FS4.4'),
    q('Ship', 'A public portfolio demo should have…', ['Real customer data', 'Seeded demo data, nightly reset, rate limits and budget caps', 'No authentication at all', 'Unlimited LLM calls'], 1, 'Safe, cheap and impressive.', 'FS4.8'),
    q('Perf', 'Good INP at the 75th percentile is…', ['≤ 200 ms', '≤ 2.5 s', '≤ 0.1', '≤ 50 ms'], 0, 'LCP ≤ 2.5 s, INP ≤ 200 ms, CLS ≤ 0.1.', 'F9.1'),
    q('Testing', 'The best fidelity for ASP.NET Core integration tests comes from…', ['EF InMemory', 'WebApplicationFactory + Testcontainers', 'Mocking DbContext', 'Manual testing'], 1, 'The real pipeline against the real engine.', 'B10.4'),
    q('Security', 'OWASP Top 10:2025 number one is…', ['Injection', 'Broken Access Control', 'Cryptographic Failures', 'SSRF'], 1, 'Authorise every request, per object, on the server.', 'S9.2'),
    q('Ops', 'Moving slow work (re-forecasting, emails) out of the request uses…', ['Thread.Sleep', 'A queue or durable job (Hangfire)', 'Bigger servers', 'Client-side code'], 1, 'Return quickly; process in the background.', 'B8.8'),
    ...BEHAVE,
  ],

  da: [
    ...SQL,
    q('Thinking', 'Before writing SQL for a vague request, you should first…', ['Pick a chart', 'Ask what decision it will inform and agree a metric definition', 'Download all data', 'Build a model'], 1, 'Question and metric first.', 'DA1.2'),
    q('Thinking', 'A metric definition must include…', ['Only a name', 'Numerator, denominator, time window and zone, filters and source', 'A colour', 'A dashboard'], 1, 'Otherwise teams report different numbers.', 'DA1.4'),
    q('Thinking', 'Churn rate is usually…', ['Lost customers ÷ customers at the start of the period', 'Lost ÷ new customers', 'New ÷ total', 'Revenue ÷ users'], 0, 'State what "lost" means.', 'DA1.5'),
    q('Thinking', 'ARPU means…', ['Average revenue per user', 'Annual recurring purchase units', 'Active retained paying users', 'Average return per unit'], 0, 'Revenue ÷ average active users.', 'DA1.5'),
    q('Thinking', 'Revenue dropped 15%. The first step is…', ['Blame marketing', 'Check the data is real (pipelines, tracking, definitions)', 'Build a model', 'Present to the CEO'], 1, 'Many drops are data bugs.', 'DA1.8'),
    q('Thinking', 'RFM segments customers by…', ['Region, frequency, margin', 'Recency, frequency, monetary value', 'Revenue, funnel, market', 'Retention, feedback, mix'], 1, 'Simple and explainable.', 'DA1.7'),
    q('Excel', 'Why is VLOOKUP risky?', ['It is slow', 'Its default is approximate match and it breaks when columns move', 'It cannot use numbers', 'It needs VBA'], 1, 'XLOOKUP defaults to exact match.', 'DA2.3'),
    q('Excel', 'In a PivotTable, % of total is set in…', ['Conditional formatting', 'Value Field Settings → Show Values As', 'Data validation', 'Power Query'], 1, '% of Grand Total, % Difference From and more.', 'DA2.5'),
    q('Excel', 'What does Power Query\'s unpivot do?', ['Deletes columns', 'Turns many value columns into attribute and value columns', 'Sorts data', 'Creates a chart'], 1, 'Wide reports become tidy long data.', 'DA2.6'),
    q('Excel', 'In Excel 365, #SPILL! means…', ['Division by zero', 'A dynamic-array result is blocked by non-empty cells', 'A circular reference', 'A missing lookup'], 1, 'Clear the cells in the way.', 'DA2.4'),
    q('SQL', 'AVG(CASE WHEN status=\'cancelled\' THEN 1.0 ELSE 0 END) computes…', ['A count', 'The cancellation rate', 'A sum', 'A median'], 1, 'The mean of a 0/1 flag is a rate.', 'DA3.3'),
    q('SQL', 'A conversion rate in SQL Server shows 0. Likely cause?', ['NULLs', 'Integer division', 'Wrong join', 'Time zones'], 1, 'Multiply by 1.0.', 'DA3.2'),
    q('SQL', 'The median in PostgreSQL is…', ['MEDIAN(x)', 'percentile_cont(0.5) WITHIN GROUP (ORDER BY x)', 'AVG(x)', 'MODE(x)'], 1, 'BigQuery uses APPROX_QUANTILES.', 'DA3.7'),
    q('SQL', 'A cohort retention table divides active users by…', ['All users ever', 'The cohort\'s size', 'Last month\'s users', 'Revenue'], 1, 'Cohort = first-activity month.', 'DA3.4'),
    q('SQL', 'Why report daily figures in Cairo time when data is stored in UTC?', ['UTC is wrong', 'Early-morning Cairo orders fall on the previous UTC day', 'Power BI needs it', 'It is faster'], 1, 'Convert before truncating to days.', 'DA3.1'),
    q('Power BI', 'A ratio such as margin % should be a…', ['Calculated column', 'Measure', 'Slicer', 'Table'], 1, 'Measures evaluate in the filter context of each visual cell.', 'DA4.4'),
    q('Power BI', 'CALCULATE…', ['Creates a table', 'Evaluates an expression in a modified filter context', 'Sorts a column', 'Imports data'], 1, 'It adds, overrides or removes filters.', 'DA4.5'),
    q('Power BI', 'Time intelligence functions require…', ['DirectQuery', 'A continuous, marked date table', 'Bidirectional relationships', 'Premium licences'], 1, 'Mark it as a date table.', 'DA4.3'),
    q('Power BI', 'Dynamic row-level security typically uses…', ['USERPRINCIPALNAME() with a security table', 'A slicer', 'Bookmarks', 'Hidden pages'], 0, 'Test with View as role.', 'DA4.9'),
    q('Power BI', 'Import vs DirectQuery: Import is…', ['Always live', 'Fastest, but as fresh as the last refresh', 'Slower', 'Only for Excel'], 1, 'DirectQuery is live but slower.', 'DA4.8'),
    q('Viz', 'Which chart for a trend over 13 months?', ['Pie', 'Line', 'Treemap', 'Scatter'], 1, 'Bars for a few periods; lines for trends.', 'DA5.2'),
    q('Viz', 'Bar charts should…', ['Start at zero', 'Use 3-D', 'Use dual axes', 'Have rotated labels'], 0, 'Bar length encodes value.', 'DA5.3'),
    q('Viz', 'A good chart title…', ['Names the variables', 'States the finding', 'Is left blank', 'Includes the date only'], 1, 'Say what the reader should take away.', 'DA5.3'),
    q('Stats', 'For salaries, report the…', ['Mean', 'Median', 'Mode', 'Maximum'], 1, 'Right-skewed data.', 'S6.1'),
    q('Stats', 'A p-value is…', ['P(null is true)', 'P(data this extreme | no effect)', 'The effect size', 'The power'], 1, 'Report the effect and CI too.', 'S6.6'),
    q('Stats', 'Which must you check before reading A/B results?', ['Sample ratio mismatch', 'Font size', 'The colour of the button', 'Server CPU'], 0, 'An unexpected split means a bug.', 'DA6.4'),
    q('Stats', 'Stopping an A/B test as soon as p < 0.05 (peeking)…', ['Is efficient', 'Inflates false positives', 'Reduces power', 'Has no effect'], 1, 'Fix the duration in advance.', 'S6.9'),
    q('Product', 'Last-touch attribution tends to over-credit…', ['Awareness channels', 'Bottom-funnel channels like branded search and retargeting', 'TV', 'Email only'], 1, 'Experiments measure incrementality.', 'DA6.5'),
    q('Product', 'Activation means…', ['Signing up', 'The first experience of the product\'s core value', 'Paying', 'Referring friends'], 1, 'E.g. first order within 7 days.', 'DA6.2'),
    q('Python', 'Chained assignment df[df.a>0]["b"]=1 in pandas 3…', ['Works', 'Never modifies df (Copy-on-Write)', 'Raises SyntaxError', 'Deletes rows'], 1, 'Use df.loc[df["a"] > 0, "b"] = 1.', 'S7.4'),
    ...BEHAVE,
  ],

  ds: [
    ...SQL.slice(0, 3), ...GIT.slice(2),
    q('Stats', 'The central limit theorem says…', ['Data is always normal', 'Sample means are approximately normal for large samples', 'Variance is constant', 'Medians equal means'], 1, 'Whatever the data\'s shape.', 'S6.4'),
    q('Stats', 'With 0.5% fraud, 99% sensitivity and 2% false positives, a flagged transaction is fraud about…', ['99% of the time', '50%', '20%', '2%'], 2, 'Base rates dominate: 495 of 2,485 flags.', 'S6.3'),
    q('Stats', 'Approximate users per group for baseline 10%, MDE 1 point, α 0.05, power 80%?', ['1,400', '14,400', '144,000', '400'], 1, '16 × 0.09 / 0.01².', 'S6.9'),
    q('Framing', 'Every feature must use only data available…', ['In the database', 'At the prediction time', 'After the label', 'In the test set'], 1, 'The target lives in a window after it.', 'DS1.3'),
    q('Framing', '"Will a discount stop this customer churning?" is a…', ['Prediction question', 'Causal question', 'Clustering question', 'Forecasting question'], 1, 'It needs experiments or uplift modelling.', 'DS1.3'),
    q('Framing', 'The threshold for a retention campaign should come from…', ['0.5 always', 'Costs and benefits, or contact capacity', 'Maximising accuracy', 'The ROC curve\'s corner'], 1, 'Expected value or top-k.', 'DS4.4'),
    q('Leakage', 'Scaling and imputing on the full dataset before splitting causes…', ['Underfitting', 'Train-test contamination (leakage)', 'Better generalisation', 'Nothing'], 1, 'Fit preprocessing inside a pipeline on training folds.', 'DS2.4'),
    q('Leakage', 'A churn model\'s top feature is "cancellation reason". This is…', ['Great feature engineering', 'Target leakage', 'Multicollinearity', 'Concept drift'], 1, 'It only exists because the customer churned.', 'DS2.4'),
    q('Leakage', 'For a customer appearing in many rows, use…', ['Random k-fold', 'Group k-fold by customer', 'No validation', 'Leave-one-out'], 1, 'Otherwise the model memorises entities.', 'DS4.2'),
    q('Features', 'Target encoding is safe when…', ['Fitted on all data', 'Computed out-of-fold with smoothing', 'Used with trees only', 'Never'], 1, 'Otherwise each row\'s own target leaks.', 'DS2.3'),
    q('Features', 'SMOTE should be applied…', ['Before splitting', 'Inside the pipeline on training folds only', 'On the test set', 'Never with trees'], 1, 'Otherwise synthetic points leak test information.', 'DS2.8'),
    q('Models', 'Bagging mainly reduces…, boosting mainly reduces…', ['bias; variance', 'variance; bias', 'variance; variance', 'bias; bias'], 1, 'Averaging independent trees vs adding trees on residuals.', 'DS3.4'),
    q('Models', 'Which model does NOT need feature scaling?', ['Logistic regression with L2', 'k-NN', 'Gradient-boosted trees', 'SVM'], 2, 'Tree splits depend on order, not scale.', 'DS3.2'),
    q('Models', 'exp(coefficient) in logistic regression is…', ['A probability', 'An odds ratio', 'The intercept', 'R²'], 1, 'Holding other features constant.', 'DS3.2'),
    q('Models', 'In gradient boosting, the number of trees is best set by…', ['Grid search', 'Early stopping on a validation set', 'Always 100', 'The number of features'], 1, 'With a small learning rate.', 'DS3.5'),
    q('Models', 'CatBoost is especially strong at…', ['Image data', 'Native handling of categorical features', 'Time series only', 'Clustering'], 1, 'Ordered target statistics avoid leakage.', 'DS3.5'),
    q('Eval', 'With 1% positives, which metric better reflects useful alerts?', ['ROC-AUC alone', 'PR-AUC', 'Accuracy', 'R²'], 1, 'Precision exposes false alarms.', 'DS4.3'),
    q('Eval', 'A model is calibrated if…', ['AUC is high', 'Predicted probabilities match observed frequencies', 'Precision equals recall', 'It has no bias'], 1, 'Fix with Platt or isotonic.', 'DS4.5'),
    q('Eval', 'SHAP values explain…', ['Causal effects in the world', 'The model\'s use of features', 'Data quality', 'Calibration'], 1, 'Associations learned by the model.', 'DS4.6'),
    q('Eval', 'Validating a model that predicts the future should use…', ['Random splits', 'Rolling time-based splits plus an out-of-time test', 'The training set', 'Stratified k-fold only'], 1, 'Never train on the future.', 'DS4.2'),
    q('Causal', 'Difference-in-differences assumes…', ['Random assignment', 'Parallel trends without treatment', 'No time effects', 'Equal group sizes'], 1, 'Check pre-period trends.', 'DS5.4'),
    q('Causal', 'CUPED reduces…', ['Bias', 'Variance, using pre-experiment data', 'Sample ratio mismatch', 'Novelty effects'], 1, 'Fewer users for the same power.', 'DS5.3'),
    q('Causal', '"Sleeping dogs" in uplift modelling are customers who…', ['Always churn', 'Never churn', 'Churn because they were contacted', 'Respond to every offer'], 2, 'Don\'t treat them.', 'DS5.6'),
    q('Causal', 'Conditioning on a collider creates…', ['A confounder', 'A false association (selection bias)', 'More power', 'Causation'], 1, 'Don\'t condition on common effects.', 'DS5.2'),
    q('Forecast', 'MASE below 1 means…', ['The model beats seasonal naive', 'The model is worse than naive', 'Perfect forecasts', 'Overfitting'], 0, 'MAE scaled by seasonal-naive in-sample MAE.', 'DS6.7'),
    q('Forecast', 'Ramadan should be modelled…', ['As calendar-month seasonality', 'With explicit Hijri-calendar features', 'Ignored', 'As a trend'], 1, 'It moves about 11 days earlier each year.', 'DS6.2'),
    q('Forecast', 'TimeGPT, Chronos and TimesFM are…', ['Databases', 'Time-series foundation models', 'Orchestrators', 'Visualisation tools'], 1, 'Zero-shot forecasts; still backtest them.', 'DS6.6'),
    q('Text', 'A strong text-classification baseline is…', ['A large LLM always', 'TF-IDF with logistic regression', 'k-means', 'PCA'], 1, 'Beat it before reaching for more.', 'DS7.3'),
    q('Clustering', 'Before k-means you should…', ['Not scale', 'Transform skewed features and scale', 'One-hot everything', 'Remove all outliers'], 1, 'k-means uses distances.', 'DS7.1'),
    q('Production', 'Training–serving skew is…', ['Class imbalance', 'Features computed differently in training and production', 'Slow inference', 'A type of drift metric'], 1, 'Share feature code or use a feature store.', 'DS8.5'),
    q('Production', 'Data drift vs concept drift: concept drift means…', ['Inputs change', 'The input–target relationship changes', 'Labels arrive late', 'The API is slow'], 1, 'It shows in performance once labels arrive.', 'DS8.6'),
    q('Production', 'Which replaced DP-100 in 2026?', ['AI-102', 'AI-300 MLOps Engineer Associate', 'DP-700', 'PL-300'], 1, 'DP-100 retired on 1 June 2026.', 'DS8.8'),
    q('Production', 'Why is loading a pickle file risky?', ['It is slow', 'It can execute arbitrary code', 'It loses precision', 'It needs GPUs'], 1, 'Only load trusted files; consider skops or ONNX.', 'DS8.3'),
    ...BEHAVE,
  ],

  de: [
    ...SQL, ...GIT.slice(0, 2),
    q('Platform', 'OLAP systems are typically…', ['Row-oriented and normalised', 'Columnar and denormalised', 'Key-value', 'In-memory only'], 1, 'Large scans and aggregations over history.', 'DE1.2'),
    q('Platform', 'A lakehouse adds what to object storage?', ['A GPU', 'A table format with ACID, schema enforcement and time travel', 'A SQL Server', 'Nothing'], 1, 'Delta Lake or Apache Iceberg.', 'DE1.3'),
    q('Platform', 'In the medallion architecture, silver holds…', ['Raw data as received', 'Cleaned, deduplicated, conformed data', 'Dashboards', 'Backups'], 1, 'Bronze raw, gold business-ready.', 'DE1.3'),
    q('Platform', 'CDC reads changes from…', ['Application logs', 'The database transaction log', 'CSV exports', 'Dashboards'], 1, 'E.g. Debezium.', 'DE1.4'),
    q('Modelling', 'The first decision when designing a fact table is…', ['The colour scheme', 'The grain', 'The partitioning', 'The BI tool'], 1, 'What one row represents.', 'DE2.2'),
    q('Modelling', 'Daily account balances are…', ['Additive', 'Semi-additive', 'Non-additive', 'Degenerate'], 1, 'Never sum them over time.', 'DE2.3'),
    q('Modelling', 'An order lifecycle with placed, picked up and delivered timestamps fits a…', ['Transaction fact', 'Periodic snapshot', 'Accumulating snapshot', 'Factless fact'], 2, 'One row per order, updated at milestones.', 'DE2.3'),
    q('Modelling', 'SCD Type 2 handles a customer moving city by…', ['Overwriting the city', 'Adding a new row with validity dates and a new surrogate key', 'Deleting the customer', 'Adding a column'], 1, 'History stays correct.', 'DE2.5'),
    q('Modelling', 'An order number kept in the fact table with no dimension is a…', ['Junk dimension', 'Degenerate dimension', 'Role-playing dimension', 'Bridge table'], 1, 'Useful for grouping lines.', 'DE2.4'),
    q('SQL', 'A MERGE fails with "update the same row more than once". Fix it by…', ['Adding an index', 'Deduplicating the source batch first', 'Using UNION', 'Disabling constraints'], 1, 'One source row per key.', 'DE3.2'),
    q('SQL', 'Which load pattern is idempotent?', ['Blind append', 'Insert-overwrite by partition', 'INSERT without keys', 'Copying files twice'], 1, 'Or MERGE on keys.', 'DE3.1'),
    q('SQL', 'Why add a lookback to a watermark extract?', ['To speed it up', 'To catch late-committed rows (requires idempotent writes)', 'To reduce cost', 'To skip duplicates'], 1, 'Overlapping rows must not duplicate.', 'DE3.1'),
    q('SQL', 'Partitioning a fact table by customer_id is usually…', ['Ideal', 'A bad idea: high cardinality creates too many tiny partitions', 'Required', 'Irrelevant'], 1, 'Partition by event date.', 'DE3.6'),
    q('Python', 'Why land raw API data before transforming it?', ['It is faster', 'So any transformation can be rerun from the original', 'APIs require it', 'To save storage'], 1, 'Bronze makes replays possible.', 'DE4.2'),
    q('Python', 'Arabic CSVs from older systems may be encoded as…', ['ASCII', 'Windows-1256 or UTF-8 with a BOM', 'EBCDIC', 'Base64'], 1, 'Read with an explicit encoding.', 'DE4.3'),
    q('Python', 'For 3 GB on one machine, a fast choice is…', ['A Spark cluster', 'Polars or DuckDB', 'Excel', 'Kafka'], 1, 'Size the tool to the data.', 'DE4.4'),
    q('Formats', 'Avro vs Parquet: Avro is…', ['Columnar', 'Row-based with schema evolution, good for streaming', 'Text-based', 'Only for images'], 1, 'Parquet suits analytics.', 'DE5.1'),
    q('Formats', 'Parquet skips row groups using…', ['Indexes in SQL Server', 'Min/max statistics in the footer', 'File names', 'Compression'], 1, 'Predicate pushdown.', 'DE5.2'),
    q('Formats', 'Delta Lake provides ACID through…', ['ZooKeeper', 'An ordered transaction log of commits', 'Row locks', 'Triggers'], 1, '_delta_log JSON commits and checkpoints.', 'DE5.3'),
    q('Formats', 'Aggressive VACUUM retention breaks…', ['Partitioning', 'Time travel to older versions', 'MERGE', 'Compression'], 1, 'Old files are physically removed.', 'DE5.6'),
    q('Spark', 'Spark stages are separated by…', ['Actions', 'Shuffles', 'Executors', 'Files'], 1, 'Wide transformations.', 'DE6.2'),
    q('Spark', 'Which is an action?', ['filter', 'select', 'write', 'withColumn'], 2, 'Actions trigger execution.', 'DE6.3'),
    q('Spark', 'Joining a huge fact with a small dimension is best done with a…', ['Sort-merge join', 'Broadcast join', 'Cross join', 'Cartesian product'], 1, 'Avoids shuffling the big table.', 'DE6.5'),
    q('Spark', 'One task runs 50× longer than the others. Likely…', ['Too many executors', 'Data skew', 'Caching', 'ANSI mode'], 1, 'AQE, special keys, broadcast or salting.', 'DE6.7'),
    q('Spark', 'coalesce(n) differs from repartition(n) because it…', ['Always shuffles', 'Merges partitions without a full shuffle', 'Increases partitions', 'Sorts data'], 1, 'Use it to reduce output files.', 'DE6.6'),
    q('Orchestration', 'Airflow tasks should use…, not datetime.now()', ['The data interval / logical date', 'A random date', 'The server clock', 'UTC midnight'], 0, 'So reruns and backfills are correct.', 'DE7.2'),
    q('Orchestration', 'XCom is meant for…', ['Large datasets', 'Small values like paths and counts', 'Secrets', 'Logs'], 1, 'Pass references, not data.', 'DE7.2'),
    q('Orchestration', 'In Airflow 3, catchup defaults to…', ['True', 'False', 'Hourly', 'It was removed'], 1, 'Set it deliberately.', 'DE7.3'),
    q('dbt', 'dbt builds the dependency graph from…', ['File names', 'ref() calls', 'Folder order', 'Comments'], 1, 'And source() for raw tables.', 'DE7.4'),
    q('dbt', 'dbt snapshots implement…', ['Backups', 'SCD Type 2 history', 'Caching', 'Partitioning'], 1, 'Automatic validity columns.', 'DE7.4'),
    q('Kafka', 'Ordering in Kafka is guaranteed…', ['Globally', 'Within a partition', 'Per broker', 'Never'], 1, 'Key related events to the same partition.', 'DE8.4'),
    q('Kafka', 'Adding consumers to a group beyond the partition count…', ['Increases throughput', 'Leaves extra consumers idle', 'Breaks ordering', 'Duplicates messages'], 1, 'Partitions cap parallelism.', 'DE8.2'),
    q('Kafka', 'Kafka 4.0 removed…', ['Partitions', 'ZooKeeper (KRaft only)', 'Consumer groups', 'Replication'], 1, 'Released March 2025.', 'DE8.2'),
    q('Streaming', 'A watermark defines…', ['The broker address', 'How late event-time data may arrive before windows close', 'The retention period', 'The partition key'], 1, 'Bounds state and lateness.', 'DE8.7'),
    q('Quality', 'Write-audit-publish means…', ['Write directly to production', 'Stage data, run checks, publish only if they pass', 'Audit logs only', 'Publish then fix'], 1, 'Consumers never see bad data.', 'DE9.2'),
    q('Quality', 'A data contract specifies…', ['Only the table name', 'Schema, semantics, quality, SLAs, ownership and change process', 'Salaries', 'The BI tool'], 1, 'Pushes quality upstream.', 'DE9.6'),
    q('Quality', 'Deleting a person\'s data in a lakehouse also requires…', ['Nothing more', 'Vacuuming or expiring old snapshots beyond retention', 'Restarting Spark', 'Renaming the table'], 1, 'Old file versions still contain it.', 'DE9.8'),
    q('Cloud', 'Microsoft\'s current data-engineering certification is…', ['DP-203', 'DP-700 (Fabric Data Engineer)', 'AZ-204', 'PL-300'], 1, 'DP-203 retired in March 2025.', 'S10.9'),
    ...BEHAVE,
  ],

  // AI Journey (sections are numbered AI<part>.<n>)
  ai: [
    q('Python', 'What does [x**2 for x in range(5) if x % 2 == 0] return?', ['[0, 4, 16]', '[1, 9]', '[0, 1, 4, 9, 16]', '[4, 16]'], 0, 'The filter keeps 0, 2 and 4; each is squared.', 'AI1.1'),
    q('NumPy', 'Adding an array of shape (3, 1) to one of shape (1, 4) gives…', ['Shape (3, 4)', 'Shape (1, 4)', 'An error', 'Shape (3, 1)'], 0, 'Broadcasting stretches size-1 dimensions virtually, without copying.', 'AI2.9'),
    q('NumPy', 'Why is a vectorised NumPy operation faster than a Python loop?', ['It uses more memory', 'The loop runs in compiled code over one contiguous, typed block of memory', 'It skips elements', 'It always runs on the GPU'], 1, 'No per-element Python overhead or type checks.', 'AI2.1'),
    q('Pandas', 'On a default RangeIndex, how many rows do df.loc[0:3] and df.iloc[0:3] return?', ['4 and 3', '3 and 3', '4 and 4', '3 and 4'], 0, 'loc is label-based with an inclusive end; iloc is position-based with an exclusive end.', 'AI3.3'),
    q('Pandas', 'groupby follows which pattern?', ['Map-filter-reduce', 'Split-apply-combine', 'Extract-transform-load', 'Sort-merge-join'], 1, 'Split rows into groups, apply a function to each, combine the results.', 'AI3.11'),
    q('Preprocessing', 'When should a StandardScaler be fitted?', ['On the full dataset before splitting', 'On the training data only, inside a Pipeline, then applied to validation and test', 'On the test set', 'Separately on each split'], 1, 'Fitting on all the data leaks test statistics into training and inflates the score.', 'AI4.0'),
    q('Preprocessing', 'A nominal feature such as city (no natural order), for a linear model, is usually encoded with…', ['Ordinal codes 0…n', 'One-hot encoding', 'Standard scaling', 'Nothing'], 1, 'Ordinal codes invent an order; one-hot does not. Use handle_unknown="ignore".', 'AI4.3'),
    q('Metrics', 'With 1% positives, a model that always predicts "negative" has an accuracy of…', ['1%', '50%', '99%', '0%'], 2, 'Accuracy hides imbalance; report precision, recall and PR-AUC instead.', 'AI8.14'),
    q('ML', 'A high training score with a much lower validation score signals…', ['Underfitting (high bias)', 'Overfitting (high variance)', 'A perfect model', 'Too little regularisation is impossible'], 1, 'The model memorised training noise; simplify, regularise or get more data.', 'AI6.4'),
    q('ML', 'In 5-fold cross-validation each sample is used for validation…', ['Never', 'Exactly once', 'Five times', 'At random'], 1, 'Each fold takes one turn as the validation set.', 'AI6.5'),
    q('ML', 'The training loss jumps around and grows with every epoch. The most likely cause is…', ['A learning rate that is too small', 'A learning rate that is too large', 'Too much data', 'Too many features'], 1, 'Steps overshoot the minimum and diverge.', 'AI6.3'),
    q('ML', 'Which validation scheme suits forecasting next month\'s demand?', ['Shuffled k-fold', 'A time-ordered split such as TimeSeriesSplit: train on the past, validate on later periods', 'Leave-one-out', 'Stratified k-fold'], 1, 'Shuffling lets the model peek at the future.', 'AI6.5'),
    q('ML', 'A first model scores 0.99 AUC offline. Your first suspicion should be…', ['Excellent work', 'Data leakage', 'Underfitting', 'Too little data'], 1, 'A feature that encodes the answer, or preprocessing fitted on all the data.', 'AI4.0'),
    q('Regression', 'Which regulariser can set some coefficients exactly to zero?', ['Ridge (L2)', 'Lasso (L1)', 'No regularisation', 'Batch normalisation'], 1, 'Ridge shrinks every coefficient; Lasso zeroes some out, which selects features.', 'AI7.17'),
    q('Regression', 'Which metric punishes a few large errors more heavily?', ['MAE', 'RMSE', 'They are identical', 'R² only'], 1, 'Squaring before averaging weights large errors more.', 'AI6.6'),
    q('Regression', 'Why drop a customer ID column before training?', ['It slows training', 'It carries no general signal and lets the model memorise rows', 'It is always null', 'scikit-learn rejects integers'], 1, 'Identifiers do not generalise to new customers.', 'AI7.3'),
    q('Classification', 'Precision answers which question?', ['Of all actual positives, how many did we catch?', 'Of everything we flagged as positive, how many were right?', 'How many predictions were correct overall?', 'How calibrated are the scores?'], 1, 'The first option is recall.', 'AI6.6'),
    q('Classification', 'For a churn-retention campaign, the course recommends optimising…', ['Accuracy', 'Recall, at a precision the offer budget can afford', 'Specificity only', 'The 0.5 threshold'], 1, 'Missing a churner usually costs more than a wasted offer; the budget caps how many you can contact.', 'AI8.14'),
    q('Classification', 'A ROC-AUC of 0.5 means the model…', ['Ranks perfectly', 'Ranks no better than random', 'Is right half the time', 'Uses a 0.5 threshold'], 1, 'AUC is the chance a random positive scores above a random negative.', 'AI8.8'),
    q('Classification', 'Why use a stratified split for an imbalanced target?', ['It is faster', 'It keeps the class ratio the same in train and test', 'It removes the minority class', 'It oversamples automatically'], 1, 'Otherwise a split can end up with very few positives.', 'AI8.4'),
    q('Classification', 'Logistic regression is trained by minimising…', ['Mean squared error', 'Log loss (cross-entropy)', 'Hinge loss', 'Gini impurity'], 1, 'Log loss punishes confident mistakes and is convex for this model.', 'AI8.13'),
    q('Trees', 'Do decision trees need feature scaling?', ['Yes, always', 'No; splits depend on the order of values, not their scale', 'Only for categorical features', 'Only with Gini'], 1, 'Thresholds are unaffected by rescaling.', 'AI8B.1'),
    q('Trees', 'A random forest reduces variance mainly by…', ['Training trees one after another on the errors', 'Averaging many trees trained on bootstrap samples with random feature subsets', 'Pruning one deep tree', 'Scaling the features'], 1, 'Decorrelated trees average out each other\'s noise.', 'AI8B.5'),
    q('Trees', 'In gradient boosting each new tree is trained to…', ['Fit the original target on its own', 'Fit the residual errors of the ensemble so far', 'Vote with the others', 'Replace the previous tree'], 1, 'Sequential error correction, scaled by the learning rate.', 'AI8B.6'),
    q('Unsupervised', 'PCA keeps the directions that…', ['Separate the classes best', 'Capture the most variance', 'Minimise the number of clusters', 'Remove outliers'], 1, 'It is unsupervised: labels play no part.', 'AI9.2'),
    q('Unsupervised', 'Why scale features before K-Means?', ['K-Means only accepts categories', 'Distances would be dominated by the largest-scale feature', 'It makes K-Means supervised', 'It is never needed'], 1, 'K-Means is distance-based.', 'AI9.7'),
    q('Unsupervised', 'Which algorithm finds odd-shaped clusters without choosing k and labels sparse points as noise?', ['K-Means', 'DBSCAN', 'PCA', 'Linear regression'], 1, 'It struggles when cluster densities differ (HDBSCAN helps).', 'AI9.18'),
    q('NLP', 'Lemmatisation differs from stemming because it…', ['Is always faster', 'Returns the dictionary form using vocabulary and part of speech', 'Removes stopwords', 'Counts words'], 1, 'Stemming chops suffixes by rule.', 'AI10.4'),
    q('NLP', 'TF-IDF gives a low weight to a word that…', ['Is rare in the corpus', 'Appears in almost every document', 'Is long', 'Is a noun'], 1, 'Inverse document frequency discounts words that are everywhere.', 'AI10.6'),
    q('NLP', 'Cosine similarity compares two vectors by…', ['Their Euclidean distance', 'The angle between them, ignoring their length', 'Their sum', 'Their largest element'], 1, 'Useful when document length should not matter.', 'AI10.7'),
    q('Stats', 'A p-value of 0.03 means…', ['A 3% chance the null hypothesis is true', 'If the null were true, data at least this extreme would appear about 3% of the time', 'The effect size is 3%', 'The test has 97% power'], 1, 'It is a statement about the data under the null, not about the null.', 'AI15.5'),
    q('Stats', 'The Central Limit Theorem says that sample means…', ['Follow the population\'s shape', 'Become approximately Normal as n grows, with standard error σ/√n', 'Are always uniform', 'Shrink to zero'], 1, 'Even for skewed data, given finite variance.', 'AI15.3'),
    q('Stats', 'Checking an A/B test every day and stopping as soon as p < 0.05…', ['Is best practice', 'Inflates the false-positive rate', 'Raises power at no cost', 'Has no effect'], 1, 'Fix the sample size with a power analysis and do not peek.', 'AI15.7'),
    q('SQL', 'Which gives a running total of revenue by date?', ['COUNT(*) … GROUP BY date', 'SUM(revenue) OVER (ORDER BY date)', 'MAX(revenue)', 'SELECT DISTINCT revenue'], 1, 'Window functions keep every row while aggregating over a frame.', 'AI12.2'),
    q('Deep learning', 'ReLU-family activations help deep networks because…', ['They are bounded', 'They keep a slope of 1 for positive inputs, so gradients do not vanish', 'They output probabilities', 'They need no weights'], 1, 'Sigmoid and tanh saturate, shrinking gradients layer by layer.', 'AI17.1'),
    q('Deep learning', 'Dropout is active…', ['During training and inference', 'Only during training', 'Only during inference', 'Only in the first layer'], 1, 'model.eval() switches it off.', 'AI17.5'),
    q('PyTorch', 'nn.CrossEntropyLoss expects the model to output…', ['Softmax probabilities', 'Raw logits', 'One-hot vectors', 'Sigmoid outputs'], 1, 'It combines log-softmax and negative log-likelihood itself.', 'AI11.13'),
    q('Vision', 'A 3×3 convolution with stride 1 and padding="same" on a 32×32 input outputs…', ['30×30', '32×32', '16×16', '34×34'], 1, '"same" zero-pads so the output matches the input.', 'AI18.2'),
    q('Vision', 'Transfer learning on a small image dataset usually starts by…', ['Training from scratch', 'Freezing a pretrained backbone and training a new head', 'Removing every convolution layer', 'Using only dense layers'], 1, 'Then unfreeze with a smaller learning rate.', 'AI18.7'),
    q('Sequences', 'LSTM and GRU cells were designed to fix…', ['Class imbalance', 'Short memory over long sequences (vanishing gradients)', 'Missing values', 'Slow tokenisation'], 1, 'Gates control what to keep and forget.', 'AI19.5'),
    q('Generation', 'Lowering the sampling temperature makes generated text…', ['More random', 'More predictable', 'Longer', 'Multilingual'], 1, 'It sharpens the distribution towards the likeliest tokens.', 'AI20.1'),
    q('Transformers', 'Self-attention produces each token\'s output as…', ['A convolution over its neighbours', 'A weighted sum of value vectors, with weights softmax(QKᵀ/√d_k)', 'The last RNN hidden state', 'A table lookup'], 1, 'Every token can attend to every other token.', 'AI21.1'),
    q('Transformers', 'BERT and GPT differ in that…', ['BERT is decoder-only', 'BERT is encoder-only (understanding); GPT is decoder-only (generation)', 'Both are encoder–decoder', 'GPT is a CNN'], 1, 'T5 and BART are the encoder–decoder family.', 'AI21.2'),
    q('LLMs', 'Retrieval-augmented generation (RAG) mainly solves…', ['Slow GPUs', 'Answering from current or private documents the model never saw, with sources', 'Tokenisation errors', 'The cost of pre-training'], 1, 'Retrieve relevant chunks, then ground the answer in them.', 'AI21.7'),
    q('Generative', 'A GAN trains…', ['One network to reconstruct its input', 'A generator against a discriminator', 'A single denoiser', 'A policy from rewards'], 1, 'The generator tries to fool the discriminator.', 'AI23.3'),
    q('Generative', 'Diffusion models generate an image by…', ['Sampling from a GAN', 'Starting from noise and removing it step by step', 'Compressing with PCA', 'Retrieving a stored image'], 1, 'They learn to reverse a fixed noising process.', 'AI23.4'),
    q('RL', 'A discount factor γ close to 0 makes an agent…', ['Far-sighted', 'Short-sighted, valuing immediate rewards', 'Random', 'Unable to learn'], 1, 'γ weights future rewards in the return.', 'AI24.4'),
    q('RL', 'Q-learning is called off-policy because…', ['It never explores', 'It learns the greedy policy while following a different, exploratory one', 'It needs a model of the environment', 'It is a policy-gradient method'], 1, 'The behaviour policy and the target policy differ.', 'AI24.7'),
    q('MLOps', 'After launch, the input data starts to look different from the training data. You watch for this as…', ['Overfitting', 'Data drift', 'Underfitting', 'Regularisation'], 1, 'Monitor input drift (PSI, missing rates, new categories), prediction drift and performance.', 'AI16.6'),
  ],

  // Connectivity Bootcamp: its own self-test exam (sections are numbered N<module>.<n>), plus eight more
  net: [
    q('Networks', 'A switch forwards traffic using which addresses?', ['IP addresses', 'MAC addresses', 'Port numbers', 'Hostnames'], 1, 'Switches are layer 2: they learn source MACs per port and forward frames by destination MAC. Routers use IPs.', 'N4.1'),
    q('Networks', 'What is the network address of 192.168.10.130/26?', ['192.168.10.0', '192.168.10.64', '192.168.10.128', '192.168.10.192'], 2, '/26 → block size 64 → subnets .0, .64, .128, .192. 130 falls in the .128 block (.129–.190 usable, .191 broadcast).', 'N2.4'),
    q('Networks', 'Which protocol resolves an IP address to a MAC address?', ['DNS', 'DHCP', 'ARP', 'ICMP'], 2, 'ARP broadcasts "who has this IP?" and caches the answering MAC: the glue between layer 3 and layer 2.', 'N3.5'),
    q('Networks', 'A PC shows IP 169.254.33.7. What happened?', ['It was hacked', 'DHCP could not be reached', 'DNS is down', 'The subnet is full'], 1, '169.254.x.x is APIPA, self-assigned after DHCP failed. Check link, VLAN, DHCP server or relay.', 'N2.3'),
    q('Networks', 'TCP port 445 belongs to…', ['RDP', 'SMB file sharing', 'HTTPS', 'LDAP'], 1, '445 = SMB/CIFS: Windows shares and mapped drives. RDP 3389, HTTPS 443, LDAP 389.', 'N3.2'),
    q('Networks', 'Which protocol is connectionless?', ['TCP', 'UDP', 'Both', 'Neither'], 1, 'UDP sends datagrams with no handshake, ACKs or ordering; used by DNS, DHCP, VoIP.', 'N3.1'),
    q('Networks', 'The TCP three-way handshake sequence is…', ['SYN → ACK → SYN-ACK', 'SYN → SYN-ACK → ACK', 'ACK → SYN → FIN', 'HELLO → ACCEPT → ACK'], 1, 'Client SYN, server SYN-ACK, client ACK; then data flows.', 'N3.1'),
    q('Networks', 'Which DNS record locates a domain\'s mail server?', ['A', 'CNAME', 'MX', 'PTR'], 2, 'MX (Mail eXchanger), with priorities. A = IPv4, CNAME = alias, PTR = reverse lookup.', 'N3.3'),
    q('Networks', 'What separates broadcast domains?', ['Hubs', 'Switches', 'Routers (and VLANs)', 'Repeaters'], 2, 'Switches flood broadcasts; routers stop them, and VLANs split a switch into several broadcast domains.', 'N4.2'),
    q('Networks', 'Frames on the native VLAN of a trunk are…', ['Double-tagged', 'Untagged', 'Encrypted', 'Dropped'], 1, 'The native VLAN travels untagged on an 802.1Q trunk; mismatched native VLANs leak traffic between VLANs.', 'N4.2'),
    q('Networks', 'STP exists to prevent…', ['IP conflicts', 'Broadcast storms from layer-2 loops', 'DNS poisoning', 'Duplex mismatches'], 1, 'Ethernet frames have no TTL; a loop multiplies broadcasts until the LAN dies. STP blocks redundant paths.', 'N4.4'),
    q('Networks', 'Administrative distance of OSPF (Cisco)?', ['90', '100', '110', '120'], 2, 'Connected 0, static 1, eBGP 20, EIGRP 90, OSPF 110, RIP 120; lower is more trusted.', 'N5.2'),
    q('Networks', 'The default route is written as…', ['255.255.255.255/32', '0.0.0.0/0', '127.0.0.1/8', '1.1.1.1/1'], 1, '0.0.0.0/0 matches everything not matched by a more specific route: the gateway of last resort.', 'N5.4'),
    q('Networks', 'Traceroute discovers each hop by manipulating…', ['The TTL field', 'The checksum', 'The MAC address', 'The window size'], 0, 'TTL = 1, 2, 3…: each router that decrements it to zero replies ICMP Time Exceeded, revealing itself.', 'N3.6'),
    q('Networks', 'Ping to 8.8.8.8 works; ping to google.com fails. The problem is…', ['The firewall', 'Routing', 'DNS', 'The NIC'], 2, 'IP connectivity is proven; only name resolution fails. Check DNS servers, nslookup, the cache.', 'N8.3'),
    q('Networks', 'Which IPsec mode encapsulates the entire original packet?', ['Transport mode', 'Tunnel mode', 'Aggressive mode', 'Main mode'], 1, 'Tunnel mode wraps the whole packet in a new one: standard for site-to-site VPNs.', 'N6.3'),
    q('Storage', 'Which RAID level needs at least 3 disks and uses single distributed parity?', ['RAID 0', 'RAID 1', 'RAID 5', 'RAID 10'], 2, 'RAID 5: capacity n−1, survives one disk, write penalty from the parity calculation.', 'N9.2'),
    q('Storage', 'Usable capacity of RAID 10 across 8 × 2 TB disks?', ['16 TB', '12 TB', '8 TB', '14 TB'], 2, 'RAID 10 mirrors then stripes: 50% usable, 8 TB.', 'N9.2'),
    q('Storage', 'A NAS typically serves storage via…', ['iSCSI and FC', 'SMB and NFS', 'SATA and SAS', 'HTTP only'], 1, 'NAS = file-level sharing (SMB for Windows, NFS for Linux/VMware). Block protocols belong to SAN.', 'N9.4'),
    q('Storage', 'In iSCSI, the client side is called the…', ['Target', 'Initiator', 'Portal', 'Fabric'], 1, 'The initiator (host) logs in to the target (array), identified by IQNs, over TCP 3260.', 'N9.4'),
    q('Storage', 'A database with heavy random reads and writes cares most about…', ['Throughput (MB/s)', 'IOPS and latency', 'Capacity', 'Compression ratio'], 1, 'Random workloads are measured in IOPS with per-operation latency; MB/s matters for sequential jobs like backups.', 'N9.1'),
    q('Storage', 'The main operational risk of thin provisioning is…', ['Slower reads', 'Pool exhaustion taking all volumes offline', 'Higher cost', 'Incompatibility with RAID'], 1, 'Oversubscribed thin pools must be monitored: hitting 100% stops every thin volume at once.', 'N9.5'),
    q('Storage', 'Restoring from a differential backup scheme needs…', ['Every differential since the full', 'The last full + the newest differential', 'Only the newest differential', 'The last two fulls'], 1, 'Differentials accumulate changes since the last full, so full + latest differential restores everything.', 'N9.6'),
    q('Storage', 'RPO measures…', ['How fast you must recover', 'How much data loss is acceptable', 'The backup window', 'Disk failure rate'], 1, 'Recovery Point Objective = acceptable data loss (time since the last good copy). RTO = time to be back up.', 'N9.6'),
    q('VMware', 'Moving a running VM between hosts with zero downtime is…', ['HA', 'vMotion', 'FT', 'Cloning'], 1, 'vMotion copies memory live across the vMotion network and switches over in under a second.', 'N10.6'),
    q('VMware', 'A host fails and its VMs restart automatically on other hosts. That is…', ['DRS', 'vMotion', 'HA', 'Snapshots'], 2, 'HA = restart-based failover (minutes of downtime). FT is the zero-downtime shadow-VM option.', 'N10.6'),
    q('VMware', 'vCenter crashes. The VMs on the ESXi hosts…', ['Power off', 'Pause', 'Keep running normally', 'Lose networking'], 2, 'ESXi does not need vCenter to run VMs; you lose central management, vMotion and DRS until it returns.', 'N10.2'),
    q('VMware', 'VM snapshot delta files are stored…', ['On the backup server', 'On the same datastore as the VM', 'In vCenter\'s database', 'In the guest OS'], 1, 'That is why snapshots are not backups and why forgotten ones fill the datastore.', 'N10.3'),
    q('VMware', 'Which is a Type 1 hypervisor?', ['VMware Workstation', 'VirtualBox', 'ESXi', 'Chrome'], 2, 'ESXi runs on bare metal. Workstation and VirtualBox run on top of a desktop OS (Type 2).', 'N10.1'),
    q('VMware', 'DRS exists to…', ['Restart failed VMs', 'Balance load across cluster hosts via vMotion', 'Back up VMs', 'Patch hosts'], 1, 'Distributed Resource Scheduler migrates VMs automatically to even out CPU and memory pressure.', 'N10.6'),
    q('VMware', 'A VMkernel port carries…', ['VM guest traffic', 'Host services: management, vMotion, storage', 'Only IPv6', 'Printer traffic'], 1, 'VMkernel interfaces are the host\'s own IP stacks for management, vMotion, iSCSI/NFS and vSAN.', 'N10.5'),
    q('VMware', 'High %RDY (CPU Ready) on a VM means…', ['The VM is idle', 'The host cannot schedule the VM\'s vCPUs: contention', 'The disk is slow', 'VMware Tools is missing'], 1, 'The VM is ready to run but waiting for physical CPU: oversubscription or limits. The classic slow-VM metric.', 'N10.7'),
    q('Linux', 'Show free disk space per filesystem:', ['du -sh', 'df -h', 'ls -lah', 'free -h'], 1, 'df -h = filesystem usage; du -sh = size of a directory tree; free -h = memory.', 'N11.3'),
    q('Linux', 'In chmod 750, the group gets…', ['rwx', 'r-x', 'r--', '---'], 1, '7 = rwx owner, 5 = r-x group, 0 = --- others.', 'N11.4'),
    q('Linux', 'Watch a log file live:', ['cat -f', 'tail -f', 'grep -f', 'less -f'], 1, 'tail -f follows the file as lines are appended: the troubleshooting staple.', 'N11.10'),
    q('Linux', 'Make a service start automatically at boot:', ['systemctl start', 'systemctl enable', 'systemctl status', 'service boot on'], 1, 'start = now; enable = at boot. Both: systemctl enable --now.', 'N11.6'),
    q('Linux', 'List listening ports and the processes that own them:', ['ip a', 'ss -tulpn', 'ping -t', 'chmod -l'], 1, 'ss (the successor of netstat) with -tulpn shows TCP/UDP listeners, ports and PIDs.', 'N11.8'),
    q('Linux', 'Configuration files traditionally live in…', ['/var', '/dev', '/etc', '/proc'], 2, '/etc holds configs; /var/log logs; /dev devices; /proc kernel state.', 'N11.2'),
    q('Linux', 'A load average of 8.0 on a 4-core server means…', ['Perfectly fine', 'Roughly twice the CPU capacity is queued', 'The server is off', '8% utilisation'], 1, 'Load ≈ runnable + I/O-waiting tasks; compare it with the core count. 8 on 4 cores = sustained queuing.', 'N11.6'),
    q('Linux', 'You deleted a huge log but df still shows the disk full. Why?', ['A reboot is always needed', 'A process still holds the deleted file open', 'df caches results', 'The file was compressed'], 1, 'Space frees when the last open handle closes: find it with lsof | grep deleted and restart that service.', 'N11.11'),
    q('Windows', 'Which event ID records an AD account lockout (and names the source computer)?', ['4625', '4740', '6008', '1074'], 1, '4740 on the DC shows the caller computer: the key to finding what is replaying an old password.', 'N12.4'),
    q('Windows', 'Group Policy processing order is…', ['OU → Domain → Site → Local', 'Local → Site → Domain → OU', 'Domain → Local → OU → Site', 'Random'], 1, 'LSDOU: later (closer) GPOs win conflicts unless enforced.', 'N12.3'),
    q('ITIL', '"The Wi-Fi is broken" vs "please create a mailbox" are…', ['Both incidents', 'Incident vs service request', 'Problem vs change', 'Both changes'], 1, 'Broken = incident (restore fast). A standard ask = service request. Root cause = problem; modification = change.', 'N13.1'),
    q('ITIL', 'Ticket priority is classically calculated from…', ['Seniority × loudness', 'Impact × urgency', 'Age × size', 'SLA × cost'], 1, 'How many / how critical (impact) times how time-sensitive (urgency) → P1–P4.', 'N13.2'),
    // eight more, from the modules the original exam covered lightly
    q('Networks', 'The four DHCP messages, in order, are…', ['Discover, Offer, Request, Acknowledge', 'Request, Offer, Discover, Acknowledge', 'Hello, Offer, Accept, Done', 'Discover, Request, Offer, Lease'], 0, 'DORA. The client broadcasts because it has no address yet.', 'N3.4'),
    q('Networks', 'At which OSI layer do routers make forwarding decisions?', ['Layer 1', 'Layer 2', 'Layer 3', 'Layer 7'], 2, 'Routers forward by IP address (network layer); switches by MAC (data link).', 'N1.5'),
    q('Wi-Fi', 'Which Wi-Fi security standard uses the SAE key exchange to resist offline password cracking?', ['WEP', 'WPA', 'WPA2-Personal', 'WPA3'], 3, 'SAE replaces the WPA2 pre-shared-key handshake and adds forward secrecy.', 'N6.1'),
    q('VPN', 'Two offices joined by a permanent tunnel between their firewalls use…', ['A remote-access VPN', 'A site-to-site VPN', 'A VLAN trunk', 'NAT only'], 1, 'Users notice nothing; remote-access VPNs are per-user clients that dial in.', 'N6.3'),
    q('Security', 'The CIA triad stands for…', ['Control, Inspection, Audit', 'Confidentiality, Integrity, Availability', 'Cipher, Identity, Access', 'Certificate, Issuer, Authority'], 1, 'Every security control protects at least one of the three.', 'N7.1'),
    q('Security', 'A stateful firewall differs from a basic packet filter because it…', ['Inspects only MAC addresses', 'Tracks connections, so replies to permitted outbound requests are allowed automatically', 'Encrypts all traffic', 'Blocks every inbound packet'], 1, 'Rules become "who may initiate what"; the state table admits the replies.', 'N7.2'),
    q('Windows', 'A domain-joined PC with a working network says it "can\'t contact the domain". First suspect?', ['The NIC driver', 'Its DNS settings: clients find domain controllers through DNS SRV records', 'The screen resolution', 'The printer'], 1, 'AD depends on DNS absolutely; point clients at the domain\'s DNS servers.', 'N12.2'),
    q('Networks', 'Why does NTP (UDP 123) matter so much in a Windows domain?', ['It speeds up file copies', 'Kerberos authentication and log correlation depend on synchronised clocks', 'It assigns IP addresses', 'It encrypts DNS'], 1, 'Clock skew breaks Kerberos logons and makes logs impossible to line up.', 'N3.2'),
  ],
};
